# Generated by Django 6.0.2 on 2026-03-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_car_category_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
