# Generated by Django 6.0.2 on 2026-03-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_booking_dropoff_location_booking_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
